/*

 LEVEL_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 162 x 20
   Tile set      : D:\workspace-gameboy\map-test-videogame-1\level_final_font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundWidth 160
#define backgroundHeight 20
//#define backgroundBank 0


extern const unsigned char background_map_levelone[];

/* End of LEVEL_1.H */
