call D:\workspace-gameboy\workspace-final-2\clean.bat
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\sound.o D:\workspace-gameboy\workspace-final-2\sound.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\splash.o D:\workspace-gameboy\workspace-final-2\splash.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\Sprites.o D:\workspace-gameboy\workspace-final-2\Sprites.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\level_1_tiles_2.o D:\workspace-gameboy\workspace-final-2\level_1_tiles_2.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\level_1.o D:\workspace-gameboy\workspace-final-2\level_1.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\world.o D:\workspace-gameboy\workspace-final-2\world.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\captions.o D:\workspace-gameboy\workspace-final-2\captions.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\background.o D:\workspace-gameboy\workspace-final-2\background.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\gamebuilder.o D:\workspace-gameboy\workspace-final-2\gamebuilder.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\collisions.o D:\workspace-gameboy\workspace-final-2\collisions.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\elementsbuilder.o D:\workspace-gameboy\workspace-final-2\elementsbuilder.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\game.o D:\workspace-gameboy\workspace-final-2\game.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2\main.o D:\workspace-gameboy\workspace-final-2\main.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -o D:\workspace-gameboy\workspace-final-2\main_1.gb D:\workspace-gameboy\workspace-final-2\sound.o D:\workspace-gameboy\workspace-final-2\splash.o D:\workspace-gameboy\workspace-final-2\main.o D:\workspace-gameboy\workspace-final-2\game.o D:\workspace-gameboy\workspace-final-2\captions.o D:\workspace-gameboy\workspace-final-2\collisions.o D:\workspace-gameboy\workspace-final-2\elementsbuilder.o D:\workspace-gameboy\workspace-final-2\background.o D:\workspace-gameboy\workspace-final-2\gamebuilder.o D:\workspace-gameboy\workspace-final-2\level_1.o D:\workspace-gameboy\workspace-final-2\level_1_tiles_2.o D:\workspace-gameboy\workspace-final-2\world.o D:\workspace-gameboy\workspace-final-2\Sprites.o