call D:\workspace-gameboy\workspace-final-2-original\clean.bat
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\sound.o D:\workspace-gameboy\workspace-final-2-original\sound.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\global.o D:\workspace-gameboy\workspace-final-2-original\global.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\splash_map.o D:\workspace-gameboy\workspace-final-2-original\splash_map.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\splash_tile_map.o D:\workspace-gameboy\workspace-final-2-original\splash_tile_map.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\splash.o D:\workspace-gameboy\workspace-final-2-original\splash.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\Sprites.o D:\workspace-gameboy\workspace-final-2-original\Sprites.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\level_1_tiles_2.o D:\workspace-gameboy\workspace-final-2-original\level_1_tiles_2.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\level_1.o D:\workspace-gameboy\workspace-final-2-original\level_1.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\world.o D:\workspace-gameboy\workspace-final-2-original\world.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\captions.o D:\workspace-gameboy\workspace-final-2-original\captions.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\background.o D:\workspace-gameboy\workspace-final-2-original\background.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\gamebuilder.o D:\workspace-gameboy\workspace-final-2-original\gamebuilder.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\collisions.o D:\workspace-gameboy\workspace-final-2-original\collisions.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\elementsbuilder.o D:\workspace-gameboy\workspace-final-2-original\elementsbuilder.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\game.o D:\workspace-gameboy\workspace-final-2-original\game.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-2-original\main.o D:\workspace-gameboy\workspace-final-2-original\main.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -o D:\workspace-gameboy\workspace-final-2-original\main_1.gb D:\workspace-gameboy\workspace-final-2-original\sound.o D:\workspace-gameboy\workspace-final-2-original\global.o D:\workspace-gameboy\workspace-final-2-original\splash_map.o D:\workspace-gameboy\workspace-final-2-original\splash_tile_map.o D:\workspace-gameboy\workspace-final-2-original\splash.o D:\workspace-gameboy\workspace-final-2-original\main.o D:\workspace-gameboy\workspace-final-2-original\game.o D:\workspace-gameboy\workspace-final-2-original\captions.o D:\workspace-gameboy\workspace-final-2-original\collisions.o D:\workspace-gameboy\workspace-final-2-original\elementsbuilder.o D:\workspace-gameboy\workspace-final-2-original\background.o D:\workspace-gameboy\workspace-final-2-original\gamebuilder.o D:\workspace-gameboy\workspace-final-2-original\level_1.o D:\workspace-gameboy\workspace-final-2-original\level_1_tiles_2.o D:\workspace-gameboy\workspace-final-2-original\world.o D:\workspace-gameboy\workspace-final-2-original\Sprites.o