call D:\workspace-gameboy\workspace-final-nomusic\clean.bat
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\sound.o D:\workspace-gameboy\workspace-final-nomusic\sound.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\global.o D:\workspace-gameboy\workspace-final-nomusic\global.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\splash_map.o D:\workspace-gameboy\workspace-final-nomusic\splash_map.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\splash_tile_map.o D:\workspace-gameboy\workspace-final-nomusic\splash_tile_map.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\splash.o D:\workspace-gameboy\workspace-final-nomusic\splash.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\Sprites.o D:\workspace-gameboy\workspace-final-nomusic\Sprites.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\level_1_tiles_2.o D:\workspace-gameboy\workspace-final-nomusic\level_1_tiles_2.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\level_1.o D:\workspace-gameboy\workspace-final-nomusic\level_1.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\world.o D:\workspace-gameboy\workspace-final-nomusic\world.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\captions.o D:\workspace-gameboy\workspace-final-nomusic\captions.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\background.o D:\workspace-gameboy\workspace-final-nomusic\background.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\gamebuilder.o D:\workspace-gameboy\workspace-final-nomusic\gamebuilder.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\collisions.o D:\workspace-gameboy\workspace-final-nomusic\collisions.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\elementsbuilder.o D:\workspace-gameboy\workspace-final-nomusic\elementsbuilder.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\game.o D:\workspace-gameboy\workspace-final-nomusic\game.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -c -o D:\workspace-gameboy\workspace-final-nomusic\main.o D:\workspace-gameboy\workspace-final-nomusic\main.c
D:\workspaces\workspaceGameBoy\gbdk-2020\bin\lcc -Wa-l -Wl-m -Wf--debug -Wl-y -Wl-w -o D:\workspace-gameboy\workspace-final-nomusic\main_1.gb D:\workspace-gameboy\workspace-final-nomusic\sound.o D:\workspace-gameboy\workspace-final-nomusic\global.o D:\workspace-gameboy\workspace-final-nomusic\splash_map.o D:\workspace-gameboy\workspace-final-nomusic\splash_tile_map.o D:\workspace-gameboy\workspace-final-nomusic\splash.o D:\workspace-gameboy\workspace-final-nomusic\main.o D:\workspace-gameboy\workspace-final-nomusic\game.o D:\workspace-gameboy\workspace-final-nomusic\captions.o D:\workspace-gameboy\workspace-final-nomusic\collisions.o D:\workspace-gameboy\workspace-final-nomusic\elementsbuilder.o D:\workspace-gameboy\workspace-final-nomusic\background.o D:\workspace-gameboy\workspace-final-nomusic\gamebuilder.o D:\workspace-gameboy\workspace-final-nomusic\level_1.o D:\workspace-gameboy\workspace-final-nomusic\level_1_tiles_2.o D:\workspace-gameboy\workspace-final-nomusic\world.o D:\workspace-gameboy\workspace-final-nomusic\Sprites.o